language: python
jobs:
  include:
    - name: 3.9 on xenial
    python: 3.9
    - name: pypy3 on xenial
    python: pypy3
    - name: 3.9 on arm64
      arch: arm64
      os: linux
      dist: focal
      python: 3.9
    - name: pypy3 on arm64
      arch: arm64
      os: linux
      dist: focal
      python: pypy3


cache: pip
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
script: pytest tests/doesthistest.py