language: python
arch:
  - amd64
  - arm64
virt:
  - lxd
os:
  - linux
dist: focal
python:
  - 3.9
  - nightly
cache: pip
install:
  - pip install -r requirements.txt
script: pytest tests/doesthistest.py

language:
  python
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - CODECOV_TOKEN='9bfaed89-7a58-4df7-b175-f5a0e63909f4'
