language: python
arch:
  - "arm64"
  - "amd64"
os: linux
dist: focal
python:
  - "3.9"
  - "pypy3"
cache: pip
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
script: pytest tests/doesthistest.py