language: python
arch:
  - arm64
  - amd64
  - arm64-graviton2
  - ppc64le
  - s390x
virt:
  - lxd
os: linux
dist: focal
python:
  - 3.9
cache: pip
install:
  - pip install -r requirements.txt
script: pytest tests/doesthistest.py