language: python
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
virt:
  - lxd
os:
  - linux
  - windows
  - osx
dist: focal
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
  - nightly
cache: pip
install:
  - pip install -r requirements.txt
script: pytest tests/doesthistest.py